"""init

Revision ID: 60669cc6b722
Revises: 
Create Date: 2025-10-15 10:25:14.734329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60669cc6b722'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('system_role', sa.String(length=64), nullable=False),
    sa.Column('resource_role', sa.String(length=64), nullable=False),
    sa.Column('subscription_plan', sa.String(length=64), nullable=False),
    sa.Column('account_status', sa.String(length=32), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verification_code_hash', sa.String(length=128), nullable=True),
    sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_channel', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(email) BETWEEN 6 AND 254', name='ck_admin_email_len'),
    sa.CheckConstraint('char_length(username) BETWEEN 4 AND 50', name='ck_admin_username_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_admin_email_ci', 'admins', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('ix_admin_username_ci', 'admins', [sa.literal_column('lower(username)')], unique=True)
    op.create_index(op.f('ix_admins_account_status'), 'admins', ['account_status'], unique=False)
    op.create_index(op.f('ix_admins_resource_role'), 'admins', ['resource_role'], unique=False)
    op.create_index(op.f('ix_admins_subscription_plan'), 'admins', ['subscription_plan'], unique=False)
    op.create_index(op.f('ix_admins_system_role'), 'admins', ['system_role'], unique=False)
    op.create_table('admin_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=32), nullable=False),
    sa.Column('contact_value', sa.String(length=128), nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_type', 'contact_value', name='ux_admin_contact_type_value')
    )
    op.create_index(op.f('ix_admin_contacts_admin_id'), 'admin_contacts', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_contacts_contact_type'), 'admin_contacts', ['contact_type'], unique=False)
    op.create_table('admins_sessions_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_admin_sessions_active', 'admins_sessions_local', ['admin_id', 'expires_at', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_admins_sessions_local_admin_id'), 'admins_sessions_local', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admins_sessions_local_family_id'), 'admins_sessions_local', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_sessions_local_family_id'), table_name='admins_sessions_local')
    op.drop_index(op.f('ix_admins_sessions_local_admin_id'), table_name='admins_sessions_local')
    op.drop_index('ix_admin_sessions_active', table_name='admins_sessions_local')
    op.drop_table('admins_sessions_local')
    op.drop_index(op.f('ix_admin_contacts_contact_type'), table_name='admin_contacts')
    op.drop_index(op.f('ix_admin_contacts_admin_id'), table_name='admin_contacts')
    op.drop_table('admin_contacts')
    op.drop_index(op.f('ix_admins_system_role'), table_name='admins')
    op.drop_index(op.f('ix_admins_subscription_plan'), table_name='admins')
    op.drop_index(op.f('ix_admins_resource_role'), table_name='admins')
    op.drop_index(op.f('ix_admins_account_status'), table_name='admins')
    op.drop_index('ix_admin_username_ci', table_name='admins')
    op.drop_index('ix_admin_email_ci', table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
